version: "3.9"

services:
  app:
    image: phpcodeigniter:latest
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=labnet"
        
        # Roteador HTTP (redirect para HTTPS)
        - "traefik.http.routers.app-http.rule=Host(`pppr.ecl.dev.br`)"
        - "traefik.http.routers.app-http.entrypoints=web"
        - "traefik.http.routers.app-http.middlewares=redirect-to-https"
        
        # Roteador HTTPS
        - "traefik.http.routers.app.rule=Host(`pppr.ecl.dev.br`)"
        - "traefik.http.routers.app.entrypoints=websecure"
        - "traefik.http.routers.app.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.app.service=app"
        
        # Service
        - "traefik.http.services.app.loadbalancer.server.port=80"
        
        # Middleware redirect
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    networks:
      - labnet
      - internal_net


  mariadb:
    image: mariadb:11
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: codeigniter
      MYSQL_USER: ciuser
      MYSQL_PASSWORD: cipass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - internal_net

volumes:
  mariadb_data:

networks:
  labnet:
    external: true   # rede já criada para Traefik
    name: labnet
  internal_net:
    driver: overlay
    name: phpcodeigniter_internal_net
    attachable: true
