name: Deploy Local com Self-Hosted Runner

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'app/**' 

# Defina a tag para a imagem local
env:
  IMAGE_TAG: phpcodeigniter:latest

jobs:
  deploy:
    # --- Ponto Chave: Direciona para o seu Self-Hosted Runner ---
    # O seu runner DEVE ter Docker e Docker Compose instalados.
    runs-on: [self-hosted, linux, x64, custom-deployer] 
    
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: 1. Build da Imagem Docker (Localmente)
        # O self-hosted runner faz o build da imagem
        run: |
          echo "Iniciando build local..."
          docker build -t ${{ env.IMAGE_TAG }} .

      - name: 2. Parar Container Anterior (Opcional)
        # Garante que a versão antiga seja derrubada antes de subir a nova
        run: |
          echo "Parando e removendo containers antigos..."
          docker compose -f docker-compose.yml down || true

      - name: 3. Deploy com Docker Compose
        # O Docker Compose usará a imagem recém-construída, 
        # que está AGORA disponível LOCALMENTE no runner.
        run: |
          echo "Iniciando deploy com Docker Compose..."
          docker compose -f docker-compose.yml up -d --build
          
      - name: Limpeza de Imagens Antigas (Opcional)
        # Remove imagens não utilizadas para liberar espaço no runner
        run: docker image prune -f