name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted  # Em vez de ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image locally
      run: |
        docker build -t phpcodeigniter:latest .
        docker tag phpcodeigniter:latest phpcodeigniter:${{ github.sha }}

    - name: Update docker-compose.yml
      run: |
        sed -i "s|image: phpcodeigniter:latest|image: phpcodeigniter:${{ github.sha }}|" docker-compose.yml

    - name: Commit and push updated docker-compose.yml
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docker-compose.yml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push