name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Generate image tag
      id: meta
      run: |
        echo "tags=emanuelluz/phpcodeigniter:latest,emanuelluz/phpcodeigniter:${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}

    - name: Update docker-compose.yml
      run: |
        sed -i "s|image: codeigniter-app:latest|image: emanuelluz/phpcodeigniter:${{ github.sha }}|" docker-compose.yml

    - name: Commit and push updated docker-compose.yml
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docker-compose.yml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push