name: CI/CD - Build and Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
      - 'modules/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  IMAGE_TAG: phpcodeigniter:latest

jobs:
  deploy:
    name: Build & Deploy (Swarm)
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_TAG }} .

      - name: Ensure Docker Swarm is active
        shell: bash
        run: |
          if ! docker info 2>/dev/null | grep -q "Swarm: active"; then
            docker swarm init
          fi

      - name: Deploy stack
        run: |
          docker stack deploy -c docker-compose.yml phpcodeigniter --with-registry-auth

      - name: Verify services
        run: |
          docker stack services phpcodeigniter

